# Generated by Django 4.1.1 on 2022-09-28 13:45

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('Job_name', models.CharField(max_length=200)),
                ('job_description', models.CharField(max_length=1000)),
                ('posted_date', models.DateField(default=django.utils.timezone.now)),
                ('current_status', models.IntegerField(default=1)),
            ],
        ),
        migrations.CreateModel(
            name='JobCandidate',
            fields=[
                ('job_candidate_id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('question_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_title', models.CharField(max_length=100)),
                ('question_description', models.CharField(max_length=1000)),
                ('question_category', models.CharField(max_length=50)),
                ('question_alternative_number', models.IntegerField(default=1)),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=30)),
                ('email_address', models.EmailField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('registered_date', models.DateField(default=django.utils.timezone.now)),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAssessor',
            fields=[
                ('question_assessor_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('assessor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
            ],
        ),
        migrations.CreateModel(
            name='QuestionAssessment',
            fields=[
                ('question_assessment_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('job_candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobcandidate')),
                ('question_assessor_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.question')),
            ],
        ),
        migrations.CreateModel(
            name='JobHistory',
            fields=[
                ('job_history_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('position', models.CharField(max_length=100)),
                ('work_place', models.CharField(max_length=100)),
                ('start_date', models.DateField(default=django.utils.timezone.now)),
                ('end_date', models.DateField(default=django.utils.timezone.now)),
                ('job_candidate_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.jobcandidate')),
            ],
        ),
        migrations.AddField(
            model_name='jobcandidate',
            name='candidate_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.AddField(
            model_name='jobcandidate',
            name='job_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job'),
        ),
        migrations.AddField(
            model_name='job',
            name='job_poster_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user'),
        ),
        migrations.CreateModel(
            name='AssignedInterviewer',
            fields=[
                ('assigned_interviewer_id', models.BigAutoField(primary_key=True, serialize=False)),
                ('interviewer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user')),
                ('job_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.job')),
            ],
        ),
    ]
